import random
# seed random number generator
random.seed()
lordlist=['Lothern']
lordlist.append('Order of Loremasters')
lordlist.append('Avelorn')
lordlist.append('Nagarythe')
lordlist.append('Hexoatl')
lordlist.append('Last Defenders')
lordlist.append('Spirit of the Jungle')
lordlist.append('Cult of Sotek')
lordlist.append('Itza')
lordlist.append('Tlaqua')
lordlist.append('Naggarond')
lordlist.append('Cult of Pleasure')
lordlist.append('Har Ganeth')
lordlist.append('The Blessed Dread')
lordlist.append('Hag Graef')
lordlist.append('Clan Mors')
lordlist.append('Clan Pestilens')
lordlist.append('Clan Rictus')
lordlist.append('Clan Skyre')
lordlist.append('The Awakened')
lordlist.append('The Dreadfleet')
lordlist.append('Pirates of Sartosa')
lordlist.append('The Drowned')
lordlist.append('Khemri')
lordlist.append('Court of Lybaras')
lordlist.append('Followers of Nagash')
lordlist.append('Exiles of Nehek')
lordlist.append('Reikland')
lordlist.append('The Golden Order')
lordlist.append('The Huntsmarshals Expedition')
lordlist.append('Karaz-a-Karak')
lordlist.append('Clan Angrund')
lordlist.append('Karak Kadrin')
lordlist.append('Black Crag')
lordlist.append('Crooked Moon')
lordlist.append('The Bloody Hands')
lordlist.append('Sylvania')
lordlist.append('Von Carstein')
lordlist.append('World Walkers')
lordlist.append('Winter Tooth')
lordlist.append('Couronne')
lordlist.append('Bordeleaux')
lordlist.append('Carcassonne')
lordlist.append('Chevaliers de Lyonesse')
lordlist.append('Talsyn')
lordlist.append('Argwylon')
lordlist.append('Beastmen')
lordlist.append('Warriors of Chaos')

def main():
    value = random.randint(0,len(lordlist))
    print(value)
    print(lordlist[value])

main()
